command_timeout = 1000000000
add_newline = false

format = """
$directory\
$git_branch\
$character"""

right_format = """$cmd_duration"""

[git_branch]
format = '[git:[\($branch\)](bold green)](bold yellow) '


[character]
success_symbol = '[⟩](bold green)'
error_symbol = '[✖](bold red)'
